Updated Bazel Instructions (#1291)
* Refine srcs glob to include and exclude patterns

Non-ASCII characters cannot be parsed by glob.

Resolves the following error when trying to build:
ERROR: /root/.cache/bazel/_bazel_root/646bcbb063181c5dac5a581e1c4fefdd/external/_main~_repo_rules~cpr/BUILD.bazel:22:6: Foreign Cc - CMake: Building cpr failed: error reading file '@@_main~_repo_rules~cpr//:test/data/test_file_hello_äüöp_2585_你好.txt': /root/.cache/bazel/_bazel_root/646bcbb063181c5dac5a581e1c4fefdd/external/_main~_repo_rules~cpr/test/data/test_file_hello_äüöp_2585_你好.txt (No such file or directory)

* Refactor Bazel setup for cpr library

Updated Bazel dependencies and build configuration for cpr.

* Update README to remove Bazel link

Removed reference to external Bazel repository due to being years out of date.